trigger:
  - master
 
pool: Default
 
variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/aishwaryabhasme22.AzureTestProject.sln'
  project: '**/aishwaryabhasme22.AzureTestProject.csproj'
 
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 
    includePreviewVersions: true
- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'NuGet tool installer'
 
- task: NuGetCommand@2
  name: 'NuGetRestore'
  displayName: 'NuGet restore packages'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

 
